# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7c2b0cfdf312f414542ab0239943c374"
name = "VIP Cashback"
application_url = "https://vip-cashback.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true


[webhooks]
api_version = "2026-10"

[[webhooks.subscriptions]]
uri = "/webhooks/orders/paid"
topics = ["orders/paid"]

[[webhooks.subscriptions]]
uri = "/webhooks/orders/create"
topics = ["orders/create"]

[[webhooks.subscriptions]]
uri = "/webhooks/orders/updated"
topics = ["orders/updated"]

[[webhooks.subscriptions]]
uri = "/webhooks/refunds/create"
topics = ["refunds/create"]

[[webhooks.subscriptions]]
uri = "/webhooks/app/scopes_update"
topics = ["app/scopes_update"]

[[webhooks.subscriptions]]
uri = "/webhooks/app/uninstalled"
topics = ["app/uninstalled"]

[[webhooks.subscriptions]]
topics = ["products/create", "products/update"]
uri = "/webhooks/products"

[events]
api_version = "unstable"

[[events.subscription]]
handle = "product-events"
topic = "Product"
actions = ["create", "update", "delete"]
uri = "/events/products"

[access_scopes]
scopes = "read_orders,read_products,write_products,read_customers"

[auth]
redirect_urls = ["https://vip-cashback.onrender.com/api/auth"]

[app_proxy]
url = "/apps/vip-access"
subpath = "vip-access"
prefix = "apps"

[product.metafields.app.demo_info]
type = "single_line_text_field"
name = "Demo Source Info"
description = "Tracks products created by the Shopify app template for development"

[product.metafields.app.demo_info.access]
admin = "merchant_read_write"

[metaobjects.app.example]
name = "Example"
description = "An example metaobject definition created by the Shopify app template"

[metaobjects.app.example.access]
admin = "merchant_read_write"

[metaobjects.app.example.fields.title]
name = "Title"
type = "single_line_text_field"
required = true

[metaobjects.app.example.fields.description]
name = "Description"
type = "multi_line_text_field"
